apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
      - name: service-registry
        image: IMAGE_URL/serviceregistry
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
spec:
  selector:
    app.kubernetes.io/name: service-registry
  ports:
    - port: 80
      targetPort: 8081